### Parallelizing Neural Network Training with PyTorch

In [15]:
import torch 
import numpy as np 
import matplotlib.pyplot as plt

In [24]:
print(torch.__version__)

2.12.0


## Creatintg Tensors in PyTorch

In [25]:
import torch
import numpy as np
np.set_printoptions(precision=3)
a = [1, 2, 3] 
b = np.array([4, 5, 6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)
tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


NameError: name 'tensor' is not defined

In [23]:
t_ones = torch.ones(2, 3)
t_ones.shape
torch.Size([2, 3])
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [26]:
rand_tensor = torch.rand(2, 3) 
print(rand_tensor)


tensor([[0.6733, 0.4464, 0.5170],
        [0.5723, 0.4708, 0.7588]])


### Manipulating the Data Types and Shape of a Tensor

In [28]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)


torch.int64


#### Transposing a Tensor:

In [29]:
t = torch.rand(3, 5)
t_tr = torch. transpose(t, 0, 1) 
print(t.shape, ' --> ', t_tr.shape)


torch.Size([3, 5])  -->  torch.Size([5, 3])


### Reshaping a Tensor (e.g. from a 1D vector to a 2D Array)

In [31]:
t = torch.zeros(30)
t_reshape = t.reshape(5, 6)
print(t_reshape.shape)

torch.Size([5, 6])


### Removing Unecessary Dimensions (dimensions having size 1, that are not needed)

In [33]:
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, '--> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1]) -->  torch.Size([1, 2, 4, 1])


### Applying Mathematical Operaitons to Tensors

In [34]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) -1 
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [35]:
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [36]:
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])


In [37]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [38]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [39]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


### Split, Stack, and Concatenate Tensors

In [40]:
torch.manual_seed(1)
t = torch.rand(6)
print(t)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


In [42]:
t_splits = torch.chunk(t, 3)
[item.numpy() for item in t_splits]

[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

#### Specify Sizes of Output Tensors Directly (instead of defining the number of splits)

In [43]:
torch.manual_seed(1)
t = torch.rand(5)
print(t)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


In [44]:
t_splits = torch.split(t, split_size_or_sections=[3,2])
[item.numpy() for item in t_splits]

[array([0.758, 0.279, 0.403], dtype=float32),
 array([0.735, 0.029], dtype=float32)]

### Concatenate Multiple Tensors

In [45]:
A = torch.ones(3)
B = torch.zeros(2)
C = torch.cat([A, B], axis=0)
print(C)

tensor([1., 1., 1., 0., 0.])


### Stacking 1D Tensors to Form A 2D Tensor

In [46]:
A = torch.ones(3)
B = torch.zeros(3)
S = torch.stack([A, B], axis=1)
print(S)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])


#### Creating a PyTorch DataLoader from Existing Tensors

In [47]:
from torch.utils.data import DataLoader 
t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)

In [48]:
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


### Creating Batches from this Dataset with a Desired Batch Size (in this example 3)

In [50]:
data_loader = DataLoader(t, batch_size=3, drop_last=False)
for i, batch in enumerate(data_loader, 1):
    print(f"batch{i}:", batch)

batch1: tensor([0., 1., 2.])
batch2: tensor([3., 4., 5.])


### Combining Two Tensors Into A Joint Dataset

In [51]:
torch.manual_seed(1)
t_x = torch.rand([4, 3], dtype=torch.float32)
t_y = torch.arange(4)

In [54]:
from torch.utils.data import Dataset
class JointDataset(Dataset):
    def __init_(self, x, y):
        self.x = x 
        self.y = y 

    def __len__(self):
        return len(self.x)

    def __getitem__(self, item):
        return self.x[idx], self.y[idx]

In [55]:
from torch.utils.data import TensorDataset
joint_dataset = TensorDataset(t_x, t_y)

In [56]:
for example in joint_dataset:
    print(' x: ', example[0], ' y: ', example[1])

 x:  tensor([0.7576, 0.2793, 0.4031])  y:  tensor(0)
 x:  tensor([0.7347, 0.0293, 0.7999])  y:  tensor(1)
 x:  tensor([0.3971, 0.7544, 0.5695])  y:  tensor(2)
 x:  tensor([0.4388, 0.6387, 0.5247])  y:  tensor(3)


In [57]:
joint_dataset = TensorDataset(t_x, t_y)

In [58]:
torch.manual_seed(1)
data_loader = DataLoader(dataset=joint_dataset, batch_size=2, shuffle=True)

In [59]:
for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}:', 'x:', batch[0],
          '\n             y:', batch[1])

batch 1: x: tensor([[0.3971, 0.7544, 0.5695],
        [0.7576, 0.2793, 0.4031]]) 
             y: tensor([2, 0])
batch 2: x: tensor([[0.7347, 0.0293, 0.7999],
        [0.4388, 0.6387, 0.5247]]) 
             y: tensor([1, 3])


### Iterate over the Batched Dataset Twice:

In [65]:
for epoch in range(2):
    print(f'Epoch {epoch+1}')
    for i, batch in enumerate(data_loader, 1):
        print(f'Batch {i}:', 'x:', batch[0],
              '\n             y:', batch[1])

Epoch 1
Batch 1: x: tensor([[0.4388, 0.6387, 0.5247],
        [0.3971, 0.7544, 0.5695]]) 
             y: tensor([3, 2])
Batch 2: x: tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]]) 
             y: tensor([0, 1])
Epoch 2
Batch 1: x: tensor([[0.7576, 0.2793, 0.4031],
        [0.4388, 0.6387, 0.5247]]) 
             y: tensor([0, 3])
Batch 2: x: tensor([[0.3971, 0.7544, 0.5695],
        [0.7347, 0.0293, 0.7999]]) 
             y: tensor([2, 1])


### Creating a Dataset From Files On a Local Storage Disk